def pull_request_factory do
  %{
    statuses_url:
      "https://api.github.com/repos/github/webook-v5/statuses/368f84f49c6ee5de4f2247d93b224629e81c5aec",
    diff_url: "https://github.com/github/webook-v5/pull/212.diff",
    number: 212,
    title: "Remove unneeded wrapper div from Preamble",
    merge_commit_sha: null,
    locked: false,
    base: build(:base),
    labels: [],
    commits: 1,
    review_comment_url: "https://api.github.com/repos/github/webook-v5/pulls/comments{/number}",
    comments_url: "https://api.github.com/repos/github/webook-v5/issues/212/comments",
    commits_url: "https://api.github.com/repos/github/webook-v5/pulls/212/commits",
    id: 277_615_553,
    merged_by: null,
    issue_url: "https://api.github.com/repos/github/webook-v5/issues/212",
    changed_files: 1,
    body:
      "## Submission Task List\r\n\r\n- ESLint\r\n  - [ ] Ensure ESLint passes\r\n- Tests\r\n  - [ ] Ensure passing tests.\r\n  - [ ] Ensure no `console.log/warn/error` or other errors appear in the output. (This can happen despite passing tests.)\r\n- Storybook\r\n  - [ ] Ensure Storybook is up-to-date with the latest changes\r\n  - [ ] Ensure Storybook compiles \r\n- Developer Console\r\n  - [ ] Ensure no errors appear in the developer console.\r\n- PropTypes\r\n  - [ ] Validate appropriate PropTypes.\r\n",
    assignees: [
      %{
        avatar_url: "https://avatars1.githubusercontent.com/u/26691?v=4",
        events_url: "https://api.github.com/users/tmilewski/events{/privacy}",
        followers_url: "https://api.github.com/users/tmilewski/followers",
        following_url: "https://api.github.com/users/tmilewski/following{/other_user}",
        gists_url: "https://api.github.com/users/tmilewski/gists{/gist_id}",
        gravatar_id: "",
        html_url: "https://github.com/tmilewski",
        id: 26691,
        login: "tmilewski",
        node_id: "MDQ6VXNlcjI2Njkx",
        organizations_url: "https://api.github.com/users/tmilewski/orgs",
        received_events_url: "https://api.github.com/users/tmilewski/received_events",
        repos_url: "https://api.github.com/users/tmilewski/repos",
        site_admin: false,
        starred_url: "https://api.github.com/users/tmilewski/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/tmilewski/subscriptions",
        type: "User",
        url: "https://api.github.com/users/tmilewski"
      }
    ],
    closed_at: null,
    user: build(:user),
    rebaseable: null,
    patch_url: "https://github.com/github/webook-v5/pull/212.patch",
    requested_teams: [
      %{
        description: "The A-Team!",
        html_url: "https://github.com/orgs/github/webhook/team-a-team",
        id: 3_174_210,
        members_url: "https://api.github.com/teams/3174210/members{/member}",
        name: "team-a-team",
        node_id: "MDQ6VGVhbTMxNzQyMTA=",
        permission: "pull",
        privacy: "closed",
        repositories_url: "https://api.github.com/teams/3174210/repos",
        slug: "team-a-team",
        url: "https://api.github.com/teams/3174210"
      }
    ],
    merged_at: null,
    additions: 2,
    mergeable: null,
    head: build(:head),
    comments: 0,
    state: "open",
    created_at: "2019-05-10T03:05:15Z",
    requested_reviewers: [],
    maintainer_can_modify: false,
    mergeable_state: "unknown",
    url: "https://api.github.com/repos/github/webook-v5/pulls/212",
    deletions: 2,
    review_comments_url: "https://api.github.com/repos/github/webook-v5/pulls/212/comments",
    draft: false,
    _links: build(:_links),
    html_url: "https://github.com/github/webook-v5/pull/212",
    node_id: "MDExOlB1bGxSZXF1ZXN0Mjc3NjE1NTUz",
    assignee: build(:assignee),
    milestone: null,
    author_association: "COLLABORATOR",
    review_comments: 0,
    merged: false,
    updated_at: "2019-05-10T03:05:15Z"
  }
end
