def repo_factory do
  %{
    statuses_url: "https://api.github.com/repos/github/webook-v5/statuses/{sha}",
    git_refs_url: "https://api.github.com/repos/github/webook-v5/git/refs{/sha}",
    issue_comment_url: "https://api.github.com/repos/github/webook-v5/issues/comments{/number}",
    watchers: 3,
    disabled: false,
    mirror_url: null,
    languages_url: "https://api.github.com/repos/github/webook-v5/languages",
    stargazers_count: 3,
    license: build(:license),
    forks: 0,
    default_branch: "develop",
    comments_url: "https://api.github.com/repos/github/webook-v5/comments{/number}",
    commits_url: "https://api.github.com/repos/github/webook-v5/commits{/sha}",
    id: 171_742_482,
    clone_url: "https://github.com/github/webook-v5.git",
    homepage: "https://fs5.netlify.com/career-courses/coding-bootcamp/denver/",
    stargazers_url: "https://api.github.com/repos/github/webook-v5/stargazers",
    events_url: "https://api.github.com/repos/github/webook-v5/events",
    blobs_url: "https://api.github.com/repos/github/webook-v5/git/blobs{/sha}",
    forks_count: 0,
    pushed_at: "2019-05-10T03:04:50Z",
    git_url: "git://github.com/github/webook-v5.git",
    hooks_url: "https://api.github.com/repos/github/webook-v5/hooks",
    owner: build(:owner),
    trees_url: "https://api.github.com/repos/github/webook-v5/git/trees{/sha}",
    git_commits_url: "https://api.github.com/repos/github/webook-v5/git/commits{/sha}",
    collaborators_url:
      "https://api.github.com/repos/github/webook-v5/collaborators{/collaborator}",
    watchers_count: 3,
    archived: false,
    tags_url: "https://api.github.com/repos/github/webook-v5/tags",
    merges_url: "https://api.github.com/repos/github/webook-v5/merges",
    releases_url: "https://api.github.com/repos/github/webook-v5/releases{/id}",
    subscribers_url: "https://api.github.com/repos/github/webook-v5/subscribers",
    ssh_url: "git@github.com:github/webook-v5.git",
    created_at: "2019-02-20T20:17:02Z",
    name: "dotcom-v5",
    has_issues: true,
    private: true,
    git_tags_url: "https://api.github.com/repos/github/webook-v5/git/tags{/sha}",
    has_projects: true,
    archive_url: "https://api.github.com/repos/github/webook-v5/{archive_format}{/ref}",
    has_wiki: true,
    open_issues_count: 8,
    milestones_url: "https://api.github.com/repos/github/webook-v5/milestones{/number}",
    forks_url: "https://api.github.com/repos/github/webook-v5/forks",
    url: "https://api.github.com/repos/github/webook-v5",
    downloads_url: "https://api.github.com/repos/github/webook-v5/downloads",
    open_issues: 8,
    keys_url: "https://api.github.com/repos/github/webook-v5/keys{/key_id}",
    description: "Password: a-team",
    contents_url: "https://api.github.com/repos/github/webook-v5/contents/{+path}",
    language: "JavaScript",
    contributors_url: "https://api.github.com/repos/github/webook-v5/contributors",
    deployments_url: "https://api.github.com/repos/github/webook-v5/deployments",
    pulls_url: "https://api.github.com/repos/github/webook-v5/pulls{/number}",
    labels_url: "https://api.github.com/repos/github/webook-v5/labels{/name}",
    html_url: "https://github.com/github/webook-v5",
    svn_url: "https://github.com/github/webook-v5",
    issue_events_url: "https://api.github.com/repos/github/webook-v5/issues/events{/number}",
    notifications_url:
      "https://api.github.com/repos/github/webook-v5/notifications{?since,all,participating}",
    has_downloads: true,
    node_id: "MDEwOlJlcG9zaXRvcnkxNzE3NDI0ODI=",
    compare_url: "https://api.github.com/repos/github/webook-v5/compare/{base}...{head}",
    full_name: "github/webook-v5",
    subscription_url: "https://api.github.com/repos/github/webook-v5/subscription",
    assignees_url: "https://api.github.com/repos/github/webook-v5/assignees{/user}",
    issues_url: "https://api.github.com/repos/github/webook-v5/issues{/number}",
    size: 2497,
    has_pages: false,
    fork: false,
    updated_at: "2019-05-08T19:33:06Z",
    branches_url: "https://api.github.com/repos/github/webook-v5/branches{/branch}",
    teams_url: "https://api.github.com/repos/github/webook-v5/teams"
  }
end
